version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: vaaniarc-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
